apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/deployments/*
      - ./k8s/services/*
build:
  # googleCloudBuild:
  #   projectId: audio-platform-323215
  local:
    push: false
  artifacts:
    # - image: us.gcr.io/audio-platform-323215/auth
    - image: jangryga/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: us.gcr.io/audio-platform-323215/user-feed
    - image: jangryga/user-feed
      context: user-feed
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: us.gcr.io/audio-platform-323215/media
    - image: jangryga/media
      context: media
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: us.gcr.io/audio-platform-323215/client
    - image: jangryga/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
