apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mydeployed-com-tls
spec:
  secretName: mydeployed-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mydeployed.com
  dnsNames:
    - mydeployed.com
    - www.mydeployed.com
