apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-feed-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-feed
  template:
    metadata:
      labels:
        app: user-feed
    spec:
      containers:
        - name: user-feed
          # image: us.gcr.io/audio-platform-323215/user-feed
          image: jangryga/user-feed
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: user-feed-srv
spec:
  selector:
    app: user-feed
  ports:
    - name: user-feed
      protocol: TCP
      port: 3000
      targetPort: 3000
