apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: media
          # image: us.gcr.io/audio-platform-323215/media
          image: jangryga/media
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: media-srv
spec:
  selector:
    app: media
  ports:
    - name: media
      protocol: TCP
      port: 3000
      targetPort: 3000
